### ISSUE TITLE
Task 3: implement the Answer table (table structure, operation functions, and testing functions)

### ISSUE THREAD

**Issue by yalgorithm777** [Disfactory/SpotDiff#12]
In this task, you need to implement the Answer table in [our data model](https://docs.google.com/presentation/d/1hyak0PdXA3CpxSC82T7ahmp0AbqjEJS2c3AcnhURpnw/edit#slide=id.gf5e3502c4a_2_0) and the related functionality.

IMPORTANT: make sure that you read the [Coding Standards section](https://github.com/Disfactory/SpotDiff#coding-standards) before writing code.

IMPORTANT: open separate branches and request code reviews to merge into the main branch when the subtasks are done.

There are three subtasks, described below:

- Subtask 1.1: implement the Answer table described in our data model as a class in the [model.py file](https://github.com/Disfactory/SpotDiff/blob/master/back-end/www/models/model.py).
- Subtask 1.2: implement the functions to operate the Answer table in the answer_operations.py file (you need to create this file) in the [model_operations folder](https://github.com/Disfactory/SpotDiff/tree/master/back-end/www/models/model_operations). You can check the [user_operations.py file](https://github.com/Disfactory/SpotDiff/blob/master/back-end/www/models/model_operations/user_operations.py) as an example.
- Subtask 1.3: implement testing functions for the Answer operations in the answer_tests.py file (you need to create this file) in the [tests folder](https://github.com/Disfactory/SpotDiff/tree/master/back-end/www/tests). You can use the [user_tests.py file](https://github.com/Disfactory/SpotDiff/blob/master/back-end/www/tests/user_tests.py) as an example.

Please reply to this issue if there are questions.

**Comment by Sourbiebie** [comment]
Wait for the decision whether to bound the bounding box with location table or answer table to complete this task.

**Comment by Sourbiebie** [comment]
Done, wait for review.
