### ISSUE TITLE
Remove unclear gold standards and add new ones

### ISSUE THREAD

**Issue by aelcenganda** [Disfactory/SpotDiff#30]
*Problems*
Very few locations are done after > 600 answers. (Location would be marked done only if two answers from qualified users, who passed the gold standard, match.

**Reasons**
Many answered the first question on landusage with 不知道(0) while the gold standards are always 1 or 2.
The gold standards were set not from the current user interface but from Google Earth, which looks different. As the result, some locations look very ambiguous for users to identify whether it was farmland or not, e.g. the aim point was put on a road or on the boundary of farmland and buildings. 

Nevertheless, the answer to the second question (new building?/New extension of existing building?) are usually quite good as it is easier to identify the changes. Those answers that didn't pass the gold standards are still usable for our research.

*Decisions*
- Disable unclear gold standards => `gold_standard_status == 3`

0: gold standard itself
1: pass gold standard
2: fail gold standard
3: disabled gold standard

- @deeper747 will give a set of gold standards to be disabled and a new set of gold standards (@dyfu95  is building another interface for @deeper747 to select the new set of goldstandards https://github.com/Disfactory/SpotDiffFrontend/issues/87)
- The data collected during April 9-13 that didn't pass the landusage gold standards (those select 0: unclear instead of 1 or 2 assigned by gold standards) keep `gold_standard_status == 2` (not passing the gold standards). We can identify these data later by timestamps.

**Comment by deeper747** [comment]
Here it is
https://docs.google.com/spreadsheets/d/10PUagSg0rgy4ycLpJKvQ24fyPk_YP0hgVYVijdlmZX0/edit?usp=sharing

**Comment by Sourbiebie** [comment]
請問是第二個sheet，82筆這個嗎？請問裡面有包含部分上次的50筆嗎？

還是之前的50筆全部mark 成作廢, 直接改用你新的檔案? (舊的全部作廢的話, 就是代表之前回答的answer 也作廢的意思了)

@deeper747

**Comment by deeper747** [comment]
82筆這個沒錯
`gold_standard_status` 那欄是`3`的就是要作廢的；`0`的是要留下來的或新增的

**Comment by Sourbiebie** [comment]
Update code and fix data.

**Comment by deeper747** [comment]
根據新的測試，我又做了一些gold standard的改動
1. 主要是把一些gold_standard_status為0但還是被答錯的改成3
2. 有一列是gold_standard_status維持0，但expansion改成2 請 @Sourbiebie 再幫我留意一下有沒有更新到。它的factoryID是d37af2be-af5c-41b5-82d3-f5f2031059e7，locationID是41

更新的goldstandard：
[20220427_answer_gold_standard.csv](https://github.com/Disfactory/SpotDiff/files/8571578/20220427_answer_gold_standard.csv)
