### ISSUE TITLE
[Data Model] Decide whether to clone or reference factory/location data from disfactory project

### ISSUE THREAD

**Issue by Sourbiebie** [Disfactory/SpotDiff#8]
Is it possible to have the table header of factory/location data from the disfactory project to proceed the discussion?
(And if possible, some data for reference)

https://docs.google.com/presentation/d/1hyak0PdXA3CpxSC82T7ahmp0AbqjEJS2c3AcnhURpnw/edit#slide=id.gf5e3502c4a_2_0

[LittleWhiteYA] 
1. 我稍微看了一下，覺得如果 city_name, town_name, lat 和 lng 都是從 factory 來的話
要不要乾脆直接就拿掉
在 query location 的時候直接 join factory table 然後再下 where 做 filter 就好
這樣可能可以避免未來 location 和 factory 資料不一致的情形發生

2.這邊會想要問說想要分開成不同 database 的原因～？
因為 location 和 factory 的關聯性看起來蠻強的，我上面的想法在建立在會放在同個 database 的基礎上

[YAlgorithm]
還沒決定 我還在用基礎的MVC架構

[ael]
可以先確認 DB 真的要分開嗎？才能談要怎麼寫 script dump 資料

[酸酸的]
我想說先瞭解一下disfactory的DB  table 如何設計的，再來討論一下是否真的需要分開

[swind]
可以請 @deeper 將 factory 的 table export 成 csv 給你，這樣上面應該就會有欄位資料，以及所有工廠的資訊了。
但是不會有其他的資訊，例如公文資訊等

**Comment by Sourbiebie** [comment]
Got CSV and API document from deeper.

**Comment by aelcenganda** [comment]
The script only needs to scrap `factory_id` to `location` table

See the Open API here 
https://api.disfactory.tw/swagger/
