### ISSUE TITLE
Task 1: implement the Location table (table structure, operation functions, and testing functions)

### ISSUE THREAD

**Issue by yalgorithm777** [Disfactory/SpotDiff#9]
In this task, you need to implement the location table in [our data model](https://docs.google.com/presentation/d/1hyak0PdXA3CpxSC82T7ahmp0AbqjEJS2c3AcnhURpnw/edit#slide=id.gf5e3502c4a_2_0) and the related functionality.

IMPORTANT: make sure that you read the [Coding Standards section](https://github.com/Disfactory/SpotDiff#coding-standards) before writing code.

IMPORTANT: open separate branches and request code reviews to merge into the main branch when the subtasks are done.

There are three subtasks, described below:

- Subtask 1.1: implement the location table described in our data model as a class in the [model.py file](https://github.com/Disfactory/SpotDiff/blob/master/back-end/www/models/model.py).
- Subtask 1.2: implement the functions to operate the location table in the location_operations.py file (you need to create this file) in the [model_operations folder](https://github.com/Disfactory/SpotDiff/tree/master/back-end/www/models/model_operations). You can check the [user_operations.py file](https://github.com/Disfactory/SpotDiff/blob/master/back-end/www/models/model_operations/user_operations.py) as an example.
- Subtask 1.3: implement testing functions for the location operations in the location_tests.py file (you need to create this file) in the [tests folder](https://github.com/Disfactory/SpotDiff/tree/master/back-end/www/tests). You can use the [user_tests.py file](https://github.com/Disfactory/SpotDiff/blob/master/back-end/www/tests/user_tests.py) as an example.

Please reply to this issue if there are questions.

**Comment by yalgorithm777** [comment]
thanks @aelcenganda for the clarifications

**Comment by Sourbiebie** [comment]
Two more questions.
1. Should the "year"(Integer) be "created_at"(datetime)? deep said it's the time the factory data created, and I guess it's the data we need to import to location table.  I'm just not sure if the date/time needs  be truncated.
2. I can't create a branch for submitting the code for this task. Would @aelcenganda help?

**Comment by aelcenganda** [comment]
`year` and `created_at` are different things.

According to the [data model](https://docs.google.com/presentation/d/1hyak0PdXA3CpxSC82T7ahmp0AbqjEJS2c3AcnhURpnw/edit#slide=id.gf5e3502c4a_2_0),
`year` is an integer attribute of `location` table to mark which year the satellite photo was taken from our geo sources. For example, `year`= 2017. It is which year the satellite image was taken.
BTW, @deeper747 , do we need to save which month of that year the satellite photo was taken? Is that information available from the source website?

 `created_at` is a datetime attribute in `factory` table that states when the factory ID was created. The location data attached to one FactoryID was created at the same time. That `created_at` logs when we scraped the data from government website or when a user added one new factory report with geo coordinates, depending on the `source` recorded in `factory` table.

**Comment by deeper747** [comment]
> BTW, @deeper747 , do we need to save which month of that year the satellite photo was taken? Is that information available from the source website?

Although it's good to have it, the "month" attribute is not available from the source.

**Comment by DotSea** [comment]
> For frontend, the red "inner bounding box," with a cross at the center, will be set to constants in pixels displayed on any devices, so that we can control the area we want users to mark can be roughly the same.
> 
> For backend, it would be nice to log coordinates (latitude, longitude) of the top left corner and the bottom right corner. Nevertheless, in my knowledge, the frontend won't directly send back coordinates of the "inner bounding box" to backend as the corner coordinates can be calculated by the center coordinates with zoom level and inner bounding box range in pixels.
> 
> Probably a better way is to store frontend display range in pixels (int) and the corner coordinates? Or is this redundant?

@aelcenganda @Sourbiebie 
I found some formula to convert pixel into lat/long, maybe it is useable to log coordinates of the inner-bounding box:
1. According to [opensteetmap wiki](https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames#Resolution_and_Scale), 1px can be converted into certain meter in different zoom-in level. For example, in zoom-in level 17 , 1px is equal to 1.1943 meters.
2. According  to [converter](https://forest.moscowfsl.wsu.edu/fswepp/rc/kmlatcon.html), we can get new location's lat/long by adding certain kilometers. (we can see it formula by Viewing Page Source "檢視原始碼")
3. As summary, if we know Latitude and longitude of the center, and Width and Height pixel of inner-bounding box, we can calculate the coordinates of the top left corner and the bottom right corner.

**Comment by yalgorithm777** [comment]
question for @aelcenganda @deeper747 @DotSea

How are we going to determine the bounding box exactly? I wonder if it is possible to just let the front-end decide it (so that the backend does not need to return the bounding box).

**Comment by Sourbiebie** [comment]
I talked to deeper yesterday. In his opinion, the bounding box should be a fixed-length/width rectangle although may need translation to pixels when displaying by the front-end. We can confirm with the front-end pals tonight.

**Comment by deeper747** [comment]
Data Flow

Backend give `FactroryID` to Frontend
Frontend request `lng` `lat` with FactoryID from disfactory.tw
Frontend request `satellite picture` from `NCU SPOT`
Frontend give `the difference of lng & lat between bounding box's corner and center` back to DB when users submit the answers

**Comment by yenchiah** [comment]
We need to think more about the last step. If the back-end receives the answer with the bounding box from the front-end, then the bounding box information should be recorded in the Answer table, not the Location table. So we will need to revise the data model.

**Comment by Sourbiebie** [comment]
Besides, I just found the bounding box center can be moved from the factory location, so the boundary box position is not bounded to the factory location any more. How about just use upper-left and lower-right point to describe the bounding box originally planed, which is more straight-forwarded? Sorry for the inconvenience. 
@deeper747 @aelcenganda

**Comment by Sourbiebie** [comment]
> We need to think more about the last step. If the back-end receives the answer with the bounding box from the front-end, then the bounding box information should be recorded in the Answer table, not the Location table. So we will need to revise the data model.

If this is confirmed, please update the data model table and I'll revise the code as well.

**Comment by Sourbiebie** [comment]
Sorry I closed it unexpectedly.

**Comment by Sourbiebie** [comment]
> We need to think more about the last step. If the back-end receives the answer with the bounding box from the front-end, then the bounding box information should be recorded in the Answer table, not the Location table. So we will need to revise the data model.

If this is confirmed, I'll update the code of location table. I have implemented the bounding box in the answer table, but waiting for the decision to pull the code of task 1 and task 3.

**Comment by yalgorithm777** [comment]
> > We need to think more about the last step. If the back-end receives the answer with the bounding box from the front-end, then the bounding box information should be recorded in the Answer table, not the Location table. So we will need to revise the data model.
> 
> If this is confirmed, I'll update the code of location table. I have implemented the bounding box in the answer table, but waiting for the decision to pull the code of task 1 and task 3.

Let's chat about this on this week's meeting.

**Comment by Sourbiebie** [comment]
Done, wait for code review.
